### ISSUE TITLE
SORRY TO BOTHER YOU, BUT CAN YOU HELP ME WITH THIS ERROR?

### ISSUE THREAD

**Issue by shuoyuanxu** [YaoZhongtian/YOLOv2-test-with-TensorFlow#2]
Traceback (most recent call last):
  File "F:/Desktop/YOLOv2/YOLO_coco_test.py", line 525, in <module>
    main()
  File "F:/Desktop/YOLOv2/YOLO_coco_test.py", line 500, in main
    yolo = YOLO_TF(len(img_set), input_size, threshold)
  File "F:/Desktop/YOLOv2/YOLO_coco_test.py", line 43, in __init__
    self.build_networks()
  File "F:/Desktop/YOLOv2/YOLO_coco_test.py", line 80, in build_networks
    self.reor_27 = self.reorg_layer(27, self.conv_26)
  File "F:/Desktop/YOLOv2/YOLO_coco_test.py", line 114, in reorg_layer
    np.expand_dims(np.tile(np.array([[1, 0], [1, 0], [0, 0], [0, 0]]), (width * channel / 4, width / 2)), 0),
  File "C:\Program Files\Anaconda3\lib\site-packages\numpy\lib\shape_base.py", line 914, in tile
    return c.reshape(shape_out)
TypeError: 'float' object cannot be interpreted as an integer

I did exactly what wrote in the README

**Comment by Abd2z** [comment]
I also got same error!!

**Comment by shuoyuanxu** [comment]
change all / to // and it works

Shuoyuan Xu
shuoyxu@gmail.com
shuoyuan.xu@cranfield.ac.uk
07756178945

2018-01-02 3:48 GMT+00:00 GooFace2 <notifications@github.com>:

**Comment by zh0ngtian** [comment]
@shuoyuanxu  is right. This error is caused by the difference between python2 and python3.

**Comment by shuoyuanxu** [comment]
i fixed it, but still thank you so much


Shuoyuan Xu
shuoyxu@gmail.com
shuoyuan.xu@cranfield.ac.uk
07756178945

2018-01-05 6:37 GMT+00:00 YaoZhongtian <notifications@github.com>:
