### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by maiminh1996** [YaoZhongtian/YOLOv2-test-with-TensorFlow#3]
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)
Loading complete!

Traceback (most recent call last):
  File "/home/minh/YOLOv2-test-with-TensorFlow/YOLO_coco_test.py", line 248, in <module>
    main()
  File "/home/minh/YOLOv2-test-with-TensorFlow/YOLO_coco_test.py", line 225, in main
    img_set_out = detect_from_pic(yolo,img_set)
  File "/home/minh/YOLOv2-test-with-TensorFlow/YOLO_coco_test.py", line 41, in detect_from_pic
    embeded[dy:dy+new_h,dx:dx+new_w,:] = resized
TypeError: slice indices must be integers or None or have an __index__ method

Could you help me?

**Comment by enengee** [comment]
The error is quite clear, maybe one of your `dx, dy, new_h, new_w` variables is float type.

**Comment by xiaofeng94** [comment]
Hi maiminh1996. This error is caused by python version.
you may try python2 instead of python3 or use int(*) to wrap every variables which raise such an error.
